import typing

def encode_varint(value: int) -> bytes: ...
def decode_varint(buffer: bytes, position: int) -> int: ...

def encode_bytes(value: bytes) -> bytes: ...
def decode_bytes(buffer: bytes, position: int) -> int: ...

def encode_zig_zag32(value: int) -> int: ...
def decode_zig_zag32(value: int) -> int: ...

def encode_zig_zag64(value: int) -> int: ...
def decode_zig_zag64(value: int) -> int: ...

def encode_header(number: int, wire_type: int) -> bytes: ...
def decode_header(buffer: bytes, position: int) -> typing.Tuple[int, int]: ...
